# Generated by Django 5.2.10 on 2026-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(editable=False, max_length=20, unique=True)),
                ('companyName', models.CharField(max_length=255)),
                ('ownerName', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('contact1', models.CharField(max_length=20)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
