# Generated by Django 5.2.10 on 2026-02-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='manifest_id',
        ),
    ]
