# Generated by Django 5.2.10 on 2026-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_remove_manifest_manifest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='destination_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='manual_product_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
