# Generated by Django 5.2.10 on 2026-02-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_manifest_destination_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='destination_address',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='manual_product_details',
        ),
    ]
