# Generated by Django 5.2.10 on 2026-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0004_rename_destination_address_manifest_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='manual_cn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
