# Generated by Django 5.2.11 on 2026-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0005_manifest_manual_cn'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
