# Generated by Django 5.2.11 on 2026-02-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0006_manifest_contact_number_manifest_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='manual_cn',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='receiver_name',
        ),
    ]
