# Generated by Django 5.2.11 on 2026-02-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0007_remove_manifest_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='device_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
