# Generated by Django 5.2.10 on 2026-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0008_manifest_device_info_manifest_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='status',
            field=models.CharField(default='In Transit', max_length=50),
        ),
    ]
