# Generated by Django 5.2.10 on 2026-02-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0009_alter_manifest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
