# Generated by Django 5.2.10 on 2026-01-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shipment',
            table='shipments',
        ),
    ]
