# Generated by Django 5.2.10 on 2026-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
