# Generated by Django 5.2.10 on 2026-02-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shipment_user_id_custom_alter_shipment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Arrived to destination', 'Arrived to destination'), ('Delivered', 'Delivered'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='products.shipment')),
            ],
            options={
                'db_table': 'shipment_tracking',
                'ordering': ['-timestamp'],
            },
        ),
    ]
