# Generated by Django 5.2.10 on 2026-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shipmenttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
