# Generated by Django 5.2.10 on 2026-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_shipmenttracking_destination_shipmenttracking_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online Payment', 'Online Payment')], max_length=20),
        ),
    ]
